# Generated by Django 4.2.7 on 2026-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of features/amenities (e.g., Pool, Garage, Garden)'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Property latitude for Google Maps', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Property longitude for Google Maps', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
